# fly.toml app configuration file generated for your-app-name-delicate-brook-1813 on 2025-07-30T15:30:57+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'your-app-name-delicate-brook-1813'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  APP_DEBUG = 'false'
  APP_ENV = 'production'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
